### PR TITLE
Added equella dropdown

### PR DESCRIPTION
**Pull request by techlead95**
image

### CODE REVIEW

**Comment by blunckr-aj** [comment]
We only want this dropdown to show up for some customers, so we need to hide or remove the elements by default, and only turn them on based on a setting in window.atomicSearchConfig. You can see in app.js that we reference this when the widget loads

**Comment by techlead95** [comment]
I got it, I'll update the PR

**Comment by blunckr-aj** [comment]
image
It doesn't show up in the mobile version of the widget. I'll ask in pivotal if it should

**Comment by techlead95** [comment]
My bad; I was thinking about it but totally missed it. I'll add it in mobile quickly.

**Comment by techlead95** [comment]
FYI, PR is updated for mobile
image

**Comment by blunckr-aj** [comment]
This looks good, let's wait to merge until it's integrated with Search so the dropdown actually does something

**Review by blunckr-aj — APPROVED** [review]

**Pull request merged**
